### PR TITLE
Fixed README links

### PR DESCRIPTION
**Pull request by MatTerra**
To Do bot link was using "-" instead of %20

### CODE REVIEW

**Comment by MatTerra** [comment]
Fixed 3 broken links;
Changed link path to make them robust to cloning

**Comment by hastagAB** [comment]
@MatTerra Thanks for your contribution. Please squash the commits so that I can merge it.

**Comment by MatTerra** [comment]
I could only squash up to 2 commits due to conflicts. The second commit is to resolve conflicts and make merging easier.

**Comment by hastagAB** [comment]
@MatTerra You should rebase instead of merge.

**Pull request merged**
