### PR TITLE
Pretty CSV

### PR DESCRIPTION
**Pull request by Frizz925**

### CODE REVIEW

**Comment by hastagAB** [comment]
@Frizz925 Please follow [Contribution Guidelines](https://github.com/hastagAB/Awesome-Python-Scripts#contribution-guidelines-)

**Comment by Frizz925** [comment]
Is there anything that I missed? I've read and followed the guidelines.

**Comment by Frizz925** [comment]
I've squashed the commits into one

**Comment by hastagAB** [comment]
> I've squashed the commits into one



> Is there anything that I missed? I've read and followed the guidelines.

Everything is good. Just one `requirements.txt` for third party libraries installation is required.

**Comment by Frizz925** [comment]
There's no third party library required, it has zero dependencies.

**Pull request merged**
