### PR TITLE
Added Fibonacci_Sequence_Generator

### PR DESCRIPTION
**Pull request by JohnWesleyK**
I have added Fibonacci_Sequence_Generator which has Fibonacci.py and README.md. Fibonacci.py is a python program that asks for user input and generates a Fibonacci Sequence based on their input. README.md has all the required information regarding requirements and running the code.

### CODE REVIEW

**Review by Kaushl2208 — CHANGES_REQUESTED** [review]
Can you update your Script name in the main README list? @JohnWesleyK

**Comment by JohnWesleyK** [comment]
> Can you update your Script name in the main README list? @JohnWesleyK

Should I make a new pull request then ?

**Comment by Kaushl2208** [comment]
> > Can you update your Script name in the main README list? @JohnWesleyK
> 
> Should I make a new pull request then ?

No need, Add a commit on this one and squash commits???

**Comment by JohnWesleyK** [comment]
> > > Can you update your Script name in the main README list? @JohnWesleyK
> > 
> > 
> > Should I make a new pull request then ?
> 
> No need, Add a commit on this one and squash commits???

Ok perfect, will squash commit it, Thanks/

**Comment by JohnWesleyK** [comment]
@Kaushl2208 I've done it, is that it ?

**Comment by Kaushl2208** [comment]
> @Kaushl2208 I've done it, is that it ?

Yes, The README is updated but Have you squashed the commits?? Because I can still see 2 commits there.

**Comment by JohnWesleyK** [comment]
I have squashed the commits, does that do the job @Kaushl2208 ??

**Comment by Kaushl2208** [comment]
> I have squashed the commits, does that do the job @Kaushl2208 ??

Hey @JohnWesleyK, Your process seems right but I guess you diverted the flow of branches and Now you are facing few merge conflicts in your file as well. I hope you love riddles because solving this will make you understand a lot about Git and its workflow.

**Comment by JohnWesleyK** [comment]
Hey @Kaushl2208 this feels like I have messed up, do you thin its bette for me to close this pull request and open another one where I fork the repo again and use a single commit, or what do you think is better for me to do?

**Comment by JohnWesleyK** [comment]
I made a [new pull request ](https://github.com/hastagAB/Awesome-Python-Scripts/pull/173), I feel like I have messed this up and due to someone modifying greetings.yml, I was getting conflicts. I'm sorry, please check the new pull request.

**Pull request closed without merging**
