### PR TITLE
python script to create github repo

### PR DESCRIPTION
**Pull request by optimist2309**

### CODE REVIEW

**Comment by hastagAB** [comment]
Hi @optimist2309, Thanks for your contribution. Please follow our [Contribution Guidelines](https://github.com/hastagAB/Awesome-Python-Scripts#contribution-guidelines-).

**Comment by optimist2309** [comment]
@hastagAB  updated my project list in readme file

**Comment by hastagAB** [comment]
> @hastagAB updated my project list in readme file

@optimist2309 Please resolve the conflicts and squash your commits.

**Comment by optimist2309** [comment]
@hastagAB  Closing this pull request

**Comment by optimist2309** [comment]
@hastagAB  Closing this pull request.

**Pull request closed without merging**
