### PR TITLE
add yoda translator

### PR DESCRIPTION
**Pull request by sonniki**
This script translates your input English sentence into Yoda-speak.

### CODE REVIEW

**Comment by hastagAB** [comment]
Great Work @sonniki ! :+1: 
Please add your script to the [Project's List](https://github.com/hastagAB/Awesome-Python-Scripts#what-do-we-have)

And don't forget to squash your commits.

**Comment by sonniki** [comment]
> Great Work @sonniki ! 
> Please add your script to the [Project's List](https://github.com/hastagAB/Awesome-Python-Scripts#what-do-we-have)

Done! Thanks!

**Comment by hastagAB** [comment]
Make a `requirements.txt` file for your Script.
And then Squash your commits., So that I can merge it.

**Comment by sonniki** [comment]
> Make a `requirements.txt` file for your Script.
> And then Squash your commits., So that I can merge it.

Also done!

**Comment by hastagAB** [comment]
Thanks for your contribution! 👍

**Pull request merged**
