### PR TITLE
Wikipedia-Search

### PR DESCRIPTION
**Pull request by Nissaar**
Created a simple Script to search Wikipedia from Python App

### CODE REVIEW

**Comment by hastagAB** [comment]
@Nissaar Please follow the [Contribution Guidelines](https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/README.md#contribuition-guidelines-).

**Comment by Nissaar** [comment]
@hastagAB Could you please point out what have I missed ?

**Comment by hastagAB** [comment]
> @hastagAB Could you please point out what have I missed ?

You'll have to add a `requirements.txt` file for your script and you need to squash your commits. Only one commit per PR is acceptable.

**Comment by Nissaar** [comment]
@hastagAB After adding the requirements.txt file, should I open another pull request?
How to squash the commits on github web interface?

**Comment by Nissaar** [comment]
@hastagAB Actually I had made the commits to the master of my forked repository

**Comment by hastagAB** [comment]
No, You can squash your commits on web UI. You have to use command line. 
Why are you even using web UI, you should be using git from command line only.
Resolve the merge conflicts and squash your commits.

**Pull request merged**
