### PR TITLE
adding file-encrypt-decrypt

### PR DESCRIPTION
**Pull request by adityaarakeri**
* `encrypts` a given file
* `decrypts` it back to original
* adding a `Readme`

### CODE REVIEW

**Comment by adityaarakeri** [comment]
In reference to #52

**Comment by adityaarakeri** [comment]
ping @hastagAB, does this PR looks good?

**Comment by hastagAB** [comment]
Nice Work @adityaarakeri ! :+1: 
Please squash your commits!

**Comment by adityaarakeri** [comment]
Commits have been squashed

**Comment by adityaarakeri** [comment]
ping @hastagAB, the commits are squashed. please merge

**Comment by hastagAB** [comment]
You have 9 commits on this PR. You haven't squashed properly.
Pull everything, delete your duplicate commits and squash the rest ones.

**Comment by adityaarakeri** [comment]
ping @hastagAB done

**Comment by hastagAB** [comment]
Thanks! :+1: 
Really appreciate the changes!

**Pull request merged**
