### PR TITLE
added Python made news generator

### PR DESCRIPTION
**Pull request by Attupatil**

### CODE REVIEW

**Review by Kaushl2208 — CHANGES_REQUESTED** [review]
@Attupatil Seems like you have not added a "How to use Readme for your scripts"

**Review by Attupatil — COMMENTED** [review]
Made the changes 
And added readme.md😊

**Comment by Kaushl2208** [comment]
> Made the changes
> And added readme.md

Please Squash the commits as well and you are good to go! :+1:

**Comment by Attupatil** [comment]
I am not really confident about squash can you help me out!?

**Comment by Kaushl2208** [comment]
> I am not really confident about squash can you help me out!?

Sure, [Git Rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) Try and go through this link and `git rebase -i` You will get good knowledge of it.

**Comment by Attupatil** [comment]
Thank you @Kaushl2208 
I guess I made some sort of error in my repo soo created New repo and pull request https://github.com/hastagAB/Awesome-Python-Scripts/pull/174
hope its fine 
Thank you.

**Pull request closed without merging**
