### PR TITLE
Add new python script

### PR DESCRIPTION
**Pull request by SuvigyaJain1**
Script can send emails to predefined circles with ease and instantly

### CODE REVIEW

**Comment by hastagAB** [comment]
Please add your script to the [Project's List](https://github.com/hastagAB/Awesome-Python-Scripts#what-do-we-have) and don't forget to squash your commits after that.

**Comment by SuvigyaJain1** [comment]
OK. Its my first time. Ill do the change as soon as possible

**Comment by hastagAB** [comment]
> OK. Its my first time. Ill do the change as soon as possible

You can always make changes to PR. 
Closing a PR like this is not a good practice.

**Comment by SuvigyaJain1** [comment]
Oh I'm sorry I wasn't aware. Is there some way I can learn how to make changes to a commit

**Pull request closed without merging**
