### PR TITLE
Akshath Mangudi - Object Detection

### PR DESCRIPTION
**Pull request by akshathmangudi**
This is my contribution to the Awesome-Python-Scripts repo. All details are in the README.md

### CODE REVIEW

**Comment by hastagAB** [comment]
@akshathmangudi thank you for your contribution. Please add your project to the main README of the repo.

**Comment by akshathmangudi** [comment]
I thought I did, when I was creating the PR, I did add it to the main README

**Comment by akshathmangudi** [comment]
@hastagAB I've updated the README.md, please review the update.

**Review by hastagAB — APPROVED** [review]
@akshathmangudi Please fix the merge conflict.

**Comment by akshathmangudi** [comment]
@hastagAB Resolved merge conflicts.

**Comment by hastagAB** [comment]
@akshathmangudi It Looks like you have unintentionally made changes in other repo files (check the `Files changed` section of the PR and the total LOC added and deleted). Please revert the commit causing this.

**Comment by akshathmangudi** [comment]
@hastagAB I've resolved the merge conflicts, however there seems to be a problem. In my branch, I'm able to see the Object-Detection and the updated README.md but once I checkout to master it disappears. And everything is up-to-date on both repositories. I'm sorry if this is becoming a nuisance, I'm just learning my way around git and open sourcing.

**Comment by hastagAB** [comment]
@akshathmangudi It's perfectly fine, we are here to learn and grow together.
Switch to your branch `akshathmangudi:Akshath` and take the latest pull and merge the changes from the upstream. If you want, you can reset the commit that seems unintentional or not needed.

**Comment by akshathmangudi** [comment]
I've resolved the conflicts. Please review the PR and let me know if any further issues have been created.

**Pull request closed without merging**
