### PR TITLE
add yts_torrents project

### PR DESCRIPTION
**Pull request by makkoncept**
There are two Scripts in this project.
`yts_am_api.py` is used to ping the official yts.am API and make simple JSON files containing the torrent links.
`linkdownload.py` is used to parse the JSON files and download the torrents.

### CODE REVIEW

**Comment by makkoncept** [comment]
@hastagAB a gentle ping!

**Comment by hastagAB** [comment]
Hello @makkoncept !
I'm not able to see your script. Please commit the appropriate files.
Don't forget to fix the conflicts and squash the commits after that.

**Comment by makkoncept** [comment]
Hey, I have pushed the changes.
The commits are now not consecutive, so the squash push from git rebase-interactive will not be what you want, also the merge will not be squashed..
Instead, you can squash and merge the PR from Github GUI itself.
Thanks!

**Comment by hastagAB** [comment]
You should have created a branch instead of master. And you can always Squash your commits from git. :)
Using GUI is not always recommended.
Anyways, thanks for your contribution, the script looks good. :+1: 
Keep Contributing!

**Pull request merged**
