### PR TITLE
Readme Fanciness Update

### PR DESCRIPTION
**Pull request by NeonNature**
- Sorted the projects alphabetically
- Adjusted some texts
- Changed to Table View for Projects
- Added **How to Use** section

### CODE REVIEW

**Comment by hastagAB** [comment]
Great work @NeonNature ! :+1: 
README Looks Awesome :tada: 

Please fix the merge conflicts and Squash your commits!

**Comment by hastagAB** [comment]
> Glad you like it. Worth the effort ^^

Yes, Thanks for your contribution. :+1: 
Please squash the commits in order to merge your PR

**Comment by NeonNature** [comment]
May I close this please? I did some terrible things on squashing and seems a new fork was a better idea. ^^ Sorry for all the trouble caused.

**Comment by hastagAB** [comment]
No Problem for me but It's not a good practice to close the PR like this. 
Git has a lot of features and you can always fix the issue no matter what it is.

**Comment by NeonNature** [comment]
I suppose. Thank you for the info 👍

**Pull request closed without merging**
