### PR TITLE
Task Scheduler for Awesome-Python-Scripts

### PR DESCRIPTION
**Pull request by heysagnik**
this adds a new project #52

### CODE REVIEW

**Comment by hastagAB** [comment]
Hi @heysagnik, please follow our [Contribution Guidelines](https://github.com/hastagAB/Awesome-Python-Scripts#contribution-guidelines)

**Comment by heysagnik** [comment]
@hastagAB is it OK now ?

**Comment by hastagAB** [comment]
@heysagnik 
Please add your project to the main README of the repo.
Ref: https://github.com/hastagAB/Awesome-Python-Scripts#steps-required-to-follow-before-adding-any-script

**Comment by heysagnik** [comment]
done @hastagAB

**Review by hastagAB — APPROVED** [review]
@heysagnik, thanks for your contribution! 🚀

**Comment by heysagnik** [comment]
please kindly add hacktoberfest tag

**Pull request merged**
