### PR TITLE
Add a .gitignore to catch common auto-generated files

### PR DESCRIPTION
**Pull request by GhostofGoes**
This will prevent people from accidentally uploading junk files to git, and save a lot of time and suffering when they have to delete those files from git. 😄

### CODE REVIEW

**Comment by GhostofGoes** [comment]
This is just related to git for the overall project. What would you want me to add to the project README?

**Comment by kaushl1998** [comment]
Yes I need you to upload that above description in a proper readme file.

**Comment by GhostofGoes** [comment]
Like...a section in the main README, or in another README in the same directory as... Yeah, I'm confused, sorry.

**Comment by GhostofGoes** [comment]
This might be helpful: https://git-scm.com/docs/gitignore

**Comment by kaushl1998** [comment]
@GhostofGoes  brother I need you to make a folder in which there will be two separate files one is the script and other one is the readme file describing the script and try to limit your commits below 3

**Comment by GhostofGoes** [comment]
This is _not_ a script, it is an improvement to the **overall** Awesome-Python-Scripts project. I'm not sure how else to explain that. If you don't know how to use git, you should read the link I commented earlier and some other resources.

**Comment by kaushl1998** [comment]
@GhostofGoes  thankyou Sir for the references!

**Pull request merged**
