### PR TITLE
Python script to view wifi password.

### PR DESCRIPTION
**Pull request by sagar627**

### CODE REVIEW

**Comment by sagar627** [comment]
Any Update?

**Review by Kaushl2208 — COMMENTED** [review]
LGTM @hastagAB , All I have to say is I am not sure about 8 commits. @sagar627  If you can squash commits that will be a great help.

**Comment by sagar627** [comment]
@Kaushl2208 I dont know how to squash commits, need help.

**Comment by sagar627** [comment]
Any update??

**Pull request merged**
