### PR TITLE
Added a cryptoconverter GUI app

### PR DESCRIPTION
**Pull request by AdnCodez**
A simple GUI of a cryptocurrency converter implemented in Python using PyQt. The UI was designed using Qt Creator.

### CODE REVIEW

**Comment by hastagAB** [comment]
Great work @AdnCodez ! :tada: 
please add yourself along with your script in the Repo's main README!

**Comment by AdnCodez** [comment]
Okay I will thank :)

**Comment by hastagAB** [comment]
Please Squash your commits so that I can merge it.

**Comment by AdnCodez** [comment]
I hope everything works good now with this commit 1c7a980; I had some trouble doing this I'm not familiar with squashing but it is a good practice for me 🤦‍♂️

**Comment by hastagAB** [comment]
You are messing up with other's commit too. Please delete all other commits you have co-authored and squash yours only.

**Pull request closed without merging**
