### PR TITLE
Adding a basic python script for codeforces

### PR DESCRIPTION
**Pull request by jineshparakh**
I have added a basic python script called Codeforces Checker
Kindly review my PR

### CODE REVIEW

**Comment by hastagAB** [comment]
Hi @jineshparakh, Thanks for your contribution. Please follow our [Contribution Guidelines](https://github.com/hastagAB/Awesome-Python-Scripts#contribution-guidelines-).

**Comment by jineshparakh** [comment]
@hastagAB  I am not getting, what have I not followed.
When I change the README file, the verification checks do not pass.
Can you let me know what else should be done so that I can make the necessary changes

**Comment by hastagAB** [comment]
> @hastagAB I am not getting, what have I not followed.
> When I change the README file, the verification checks do not pass.
> Can you let me know what else should be done so that I can make the necessary changes

@jineshparakh You've to add your script in the [Project's list](https://github.com/hastagAB/Awesome-Python-Scripts#what-do-we-have) in the main README. This helps us to keep track of all the projects.

**Comment by jineshparakh** [comment]
@hastagAB I have created a new pull request because I did not have the old instance of the fork with me. I will close this PR now, please review the new one, I have updated the README file in that request.

**Pull request closed without merging**
